baseURL = "https://vaibhawchandel.github.io/notes/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AI.ML.DL"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
googleAnalytics = "UA-120896798-1"
disqusShortname = "vaibhawchandel-notes"

[params]
  editURL = "https://github.com/vaibhawchandel/notes/edit/master/content/"
  description = "Notes"
  author = "Vaibhaw Singh Chandel"
  showVisitedLinks = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/vaibhawchandel/notes"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 20
